### ISSUE TITLE
A question about the pre-trained weights

### ISSUE THREAD

**Issue by CamillaBressan** [postor/DOTA-yolov3#10]
Dear Postor, 
Thank you so much for the work you put in developing this code, it is very well functioning and well written. I had a question about the pre-trained weights that you provide, as I'd like to use them as a baseline for some experiments. 

* Was the model trained on the full TRAIN DOTA dataset?
* How many epochs did the training run for?
* For curiosity, how long did the training take? Which hardware (types and number of GPUs) did you use?

Thank you so much in advance for your time!

**Comment by postor** [comment]
- not full, only training dataset used, 2 years has passed I believe the dataset has grow, and plus you can add validate set into training to gain better result
- forgot
- some hours with RTX2080Ti

**Comment by CamillaBressan** [comment]
Thank you for your reply!
