### ISSUE TITLE
权重训练时的尺寸

### ISSUE THREAD

**Issue by juechenzp** [postor/DOTA-yolov3#2]
请问您的权重文件训练时的切片尺寸是多大？

**Comment by postor** [comment]
1024，详情参考代码https://github.com/postor/DOTA-yolov3/blob/master/data_transform/split.py

**Comment by juechenzp** [comment]
非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "junjun"<notifications@github.com&gt;; 
发送时间: 2020年4月24日(星期五) 下午4:58
收件人: "postor/DOTA-yolov3"<DOTA-yolov3@noreply.github.com&gt;; 
抄送: "绝尘"<1501799452@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [postor/DOTA-yolov3] 权重训练时的尺寸 (#2)





 
1024，详情参考代码https://github.com/postor/DOTA-yolov3/blob/master/data_transform/split.py
