### ISSUE TITLE
darknet: command not found

### ISSUE THREAD

**Issue by incredible-john** [postor/DOTA-yolov3#4]
Hi, i follow your instructions and stuck at the 'train' step when i ran the command "darknet detector train dota.data dota-yolov3-tiny.cfg"

it said: "darknet: command not found" (darknet: 未找到命令)

i have installed the darknet but probably not the in the right directory

May i ask in which directory did you installed darknet and can you give me some detials about the darknet installation?

**Comment by postor** [comment]
put darknet into /usr/bin or windows system32 for short answer, for more you can search system path your self

**Comment by incredible-john** [comment]
Thank you very much for your advice !!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "junjun"<notifications@github.com&gt;; 
发送时间: 2020年4月27日(星期一) 上午8:42
收件人: "postor/DOTA-yolov3"<DOTA-yolov3@noreply.github.com&gt;; 
抄送: "张世钊"<1187052641@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [postor/DOTA-yolov3] darknet: command not found (#4)





 
put darknet into /usr/bin or windows system32 for short answer, for more you can search system path your self
