### ISSUE TITLE
container-crane class?

### ISSUE THREAD

**Issue by incredible-john** [postor/DOTA-yolov3#5]
Hi, I wonder why container-crane class is included in the <dota_utils.py>, because there is no container-crane class in the original DOTA dataset.

**Comment by postor** [comment]
It's just some code from other repo, I won't modify it as long as it works, you can do whatever to the codes as you like to find why

**Comment by incredible-john** [comment]
Ok, thanks for your reply!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "junjun"<notifications@github.com&gt;; 
发送时间: 2020年4月27日(星期一) 上午8:44
收件人: "postor/DOTA-yolov3"<DOTA-yolov3@noreply.github.com&gt;; 
抄送: "张世钊"<1187052641@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [postor/DOTA-yolov3] container-crane class? (#5)





 
It's just some code from other repo, I won't modify it as long as it works, you can do whatever to the codes as you like to find why
