### ISSUE TITLE
train question

### ISSUE THREAD

**Issue by mary-0830** [postor/DOTA-yolov3#6]
Hello, may I ask the following prompt when trying to run
“darknet detector train dota.data dota-yolov3-tiny.cfg”

Why is this? I watched your video and I didn't see darknet in the cfg. I don't know what went wrong?
thank you for your reply.

**Comment by postor** [comment]
do you have a screen shot?

**Comment by mary-0830** [comment]
I downloaded darknet in cfg, and then copied the contents of the previous cfg in darknet/cfg to train.

I still have a few questions:
1. Can your code calculate the map of each category?
2. Will the pre-training weights you gave on Baidu Cloud continue training?
3. I want to use yolov3 as the baseline. Am I retraining? How to get the weight of DOTA? Or continue training on the pre-training weights you give?

thank you for your reply.

**Comment by postor** [comment]
I don't think contiue training can get better result, enough epoches I think. still you can try anything you want, yes, on yourself
