### ISSUE TITLE
Floating point exception when training

### ISSUE THREAD

**Issue by Runkli** [postor/DOTA-yolov3#7]
I have followed the tutorial and made sure directories, dependencies, etc. are all met. However, when running the command:
```darknet detector train dota.data dota-yolov3-416.cfg``` I get the following output:
```
[CNN model info here]
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
608
Floating point exception (core dumped)
``` 
This occurs in both the tiny and the original file. What could cause this?

**Comment by postor** [comment]
maybe hardware not good enough

**Comment by Runkli** [comment]
I have a GTX1050ti for my training, one possibility is that each time it resizes to a different value. Every time I run it, after it prints "Resizing", i get a different value. Could this be the cause? If so what could I change

**Comment by postor** [comment]
probably, my GTX1050  wont work, the video was using RTX2080ti, not sure how good it really needs, you can try lower batchsize higer subvision, might or might not work

**Comment by Runkli** [comment]
The problem was the train.txt and val.txt, the paths were not set correctly. After that it seems to be running fine so far.
