### ISSUE TITLE
Error while calculating anchors

### ISSUE THREAD

**Issue by himanshugiriraj** [postor/DOTA-yolov3#8]
Hi,
i am having GPU GTX 1650 (4GB RAM)
when training yolov3-tiny i changed the max batches and for that i need to recalculate anchors however whenever i tried for that it shows:
 **calculating k-means++ ...
Segmentation fault (core dumped)**

i am calculating anchors using:
./darknet detector calc_anchors DOTA-yolov3/cfg/dota.data -num_of_clusters 6 -width 416 -height 416 -show

can you please suggest me where i did wrong..?

Another issue if i train model using provided cfg my avg loss shows 0.0000 even after 2000 iterations..
![chart_dota-yolov3-tiny](https://user-images.githubusercontent.com/56444068/95025302-511b1800-06a6-11eb-9c72-d8b48cf84e73.png)
![Screenshot from 2020-10-05 01-02-13](https://user-images.githubusercontent.com/56444068/95025342-97707700-06a6-11eb-9e57-b227bdcf4605.png)

**Comment by himanshugiriraj** [comment]
and one more thing how can i change the max value displays on loss...

**Comment by postor** [comment]
please check `Can't open label file` may be access rights or none file exit at all
