### ISSUE TITLE
How to deal with the .txt files under the Train_Task2_gt.zip and Val_Task2_gt.zip?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [postor/DOTA-yolov3#9]
Hi,
    I have downloaded the "DOTA" data set, and found there are "..._gt.zip" under the "labelTxt" folder.
![100](https://user-images.githubusercontent.com/72843232/136761510-7f1641fc-ba10-4ee3-af33-c34da97d3e77.png)
![101](https://user-images.githubusercontent.com/72843232/136761520-bcc857e3-5633-4a91-bfde-54c45fa11dca.png)

    I am very sure that "labelTxt.zip" will be put in the structure as the name "labelTxt". However, I am so confused about how to deal with the ".txt" files under the "..._Task2_gt" folder?
    So, could you pls give me some suggestions? Thanks!

**Comment by postor** [comment]
what happens if you just ignore it?  two years has passed and I've no idea too 😢, are they in the same format as labelTxt? maybe they label defferent things?
最近没有关注数据集的更新，欢迎加我微信 postor 讨论
